og_dict = {
    'a':"odoo gogs", 
    'b':"gogs odoo odoo odoo", 
    'c':"gogs odoo gogs odoo", 
    'd':"gogs odoo odoo", 
    'e':"odoo", 
    'f':"odoo odoo gogs odoo", 
    'g': "goggs goggs odoo", 
    'h': "odoo odoo odoo odoo", 
    'i': "odoo odoo", 
    'j': "odoo gogs gogs gogs", 
    'k':"gogs odoo gogs", 
    'l':"odoo gogs odoo odoo", 
    'm':"gogs gogs", 
    'n':"gogs odoo", 
    'o':"gogs gogs gogs", 
    'p':"odoo gogs gogs odoo", 
    'q':"gogs gogs odoo gogs", 
    'r':"odoo gogs odoo", 
    's':"odoo odoo odoo", 
    't':"gogs", 
    'u':"odoo odoo gogs", 
    'v':"odoo odoo odoo gogs", 
    'w':"odoo gogs gogs", 
    'x':"gogs odoo odoo gogs", 
    'y':"gogs odoo gogs gogs", 
    'z':"gogs gogs odoo odoo",
    '.':'.',
    ',':','
    }
